### ISSUE TITLE
MetaFiles are not optimized

### ISSUE THREAD

**Issue by diger74** [diger74/DeleteAgency.Kentico12.ImageMagick#1]
When uploading the image for Product (SKU) it is stored as MetaFile and optimization is not happening.

**Comment by mighty-nyaina** [comment]
Hi @diger74 
I have the same issue, did you find any solutions ?

**Comment by diger74** [comment]
Hi @mighty-nyaina 
The latest release of Nuget package (1.1.0) can optimize attachments and meta files: https://www.nuget.org/packages/DeleteAgency.Kentico12.ImageMagick/
Please try it and let me know.

**Comment by mighty-nyaina** [comment]
@diger74 
Same issue with the latest release
Thanks

**Comment by diger74** [comment]
@mighty-nyaina could you please provide a bit more info on how to reproduce the issue and how do you use the module? Have you updated the module from 1.0.0 to 1.1.0 or installed 1.1.0 from fresh? Do you have workflow enabled? Any other relevant info?

I've just tested it and product images (aka meta files) are optimized.
