### ISSUE TITLE
Installation steps for K12 MVC

### ISSUE THREAD

**Issue by jknopp** [diger74/DeleteAgency.Kentico12.ImageMagick#2]
Awesome project, I was looking at the source code and was curious why the NuGet needs to be installed in both the MVC project and the CMSApp Kentico Admin project?

It seems like the functionality is all related to the CMSApp Kentico Admin project and events that occur when files are updated within the Admin. Can you help me understand what is needed on the MVC side for the NuGet to be installed there?

I am following this documentation section: https://docs.kentico.com/k12sp/custom-development/creating-custom-modules#Creatingcustommodules-Modulesdeployedviainstallationpackages
And was going to include the NuGet in a separate project within the Kentico solution. 

However, under this section: https://docs.kentico.com/k12sp/custom-development/creating-custom-modules#Creatingcustommodules-Compilingmodulecodeintoassemblies
It notes, "When utilizing the MVC development model, you may need to deploy the assembly containing your module's code to the separate MVC application (in addition to the Kentico administration project). This is necessary for any module classes whose data you wish to display or otherwise use on your live site, and for modules that modify the system's live site functionality". 

That isn't the case here, correct? There is no live site data or functionality changes correct, or am I missing something?

Thanks!

**Comment by jknopp** [comment]
Or did I just misunderstand this line in the README:
"Install **DeleteAgency.Kentico12.ImageMagick** NuGet package for **both** Kentico CMS and MVC solutions".

And it just means it can be installed only in the CMSApp Kentico Admin project of either type of solution?

**Comment by diger74** [comment]
Hi! Thanks 

There are some scenarios when images are managed from MVC application, refer to this [Media Selection MVC control](https://docs.kentico.com/k12sp/developing-websites/page-builder-development/page-and-media-selectors-for-page-builder-components) for example. In this case, if the media file or attachment is uploaded through MVC control and image optimization code (as well as global event handler on insert or update of the media item) won't be there - the image will be uploaded non-optimized. Kentico fires events only instance where they actually happen, i.e. if you add new media file via MVC application, media file insert event will only be raised in MVC and CMS (mother) will not receive or process this event. Hope it makes more sense now but feel free to drop any other questions.

**Comment by jknopp** [comment]
Thanks for letting me know, that makes totally sense and I do see why that would be required. I'm going to do a little more testing with that in mind and let you know if I have any other questions.

Appreciate it!
